<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://soap.training.mulesoft.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TicketServiceService" targetNamespace="http://soap.training.mulesoft.com/">
   <wsdl:types>
      <xsd:schema targetNamespace="http://tempuri.org/Imports">
         <xsd:import schemaLocation="imported-schema.xsd" namespace="http://soap.training.mulesoft.com/"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="listAllFlightsResponse">
      <wsdl:part element="tns:listAllFlightsResponse" name="parameters" />
   </wsdl:message>
   <wsdl:message name="findFlight">
      <wsdl:part element="tns:findFlight" name="parameters" />
   </wsdl:message>
   <wsdl:message name="findFlightResponse">
      <wsdl:part element="tns:findFlightResponse" name="parameters" />
   </wsdl:message>
   <wsdl:message name="listAllFlights">
      <wsdl:part element="tns:listAllFlights" name="parameters" />
   </wsdl:message>
   <wsdl:portType name="TicketService">
      <wsdl:operation name="listAllFlights">
         <wsdl:input message="tns:listAllFlights" name="listAllFlights" />
         <wsdl:output message="tns:listAllFlightsResponse" name="listAllFlightsResponse" />
      </wsdl:operation>
      <wsdl:operation name="findFlight">
         <wsdl:input message="tns:findFlight" name="findFlight" />
         <wsdl:output message="tns:findFlightResponse" name="findFlightResponse" />
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="TicketServiceServiceSoapBinding" type="tns:TicketService">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
      <wsdl:operation name="listAllFlights">
         <soap:operation soapAction="" style="document" />
         <wsdl:input name="listAllFlights">
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output name="listAllFlightsResponse">
            <soap:body use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="findFlight">
         <soap:operation soapAction="" style="document" />
         <wsdl:input name="findFlight">
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output name="findFlightResponse">
            <soap:body use="literal" />
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="TicketServiceService">
      <wsdl:port binding="tns:TicketServiceServiceSoapBinding" name="TicketServicePort">
         <soap:address location="http://mule-worker-training.cloudhub.io:8081/essentials/delta" />
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
